namespace: "packetferret"
name: "juniper_build_config"
version: "0.0.1"
readme: "README.md"
authors:
    - "Calvin Remsburg (@packetferret)"
dependencies:
    "juniper.junos": ">=2.3.0,<3.0.0"
license:
    - "MIT"
tags:
    - network
    - collection
repository: "https://www.github.com/packetferret/juniper_build_config"