namespace: "packetferret"
name: "juniper_build_config"
version: "0.0.2"
readme: "README.md"
authors:
    - "Calvin Remsburg (@packetferret)"
license:
    - "MIT"
tags:
    - network
    - collection
repository: "https://www.github.com/packetferret/juniper_build_config"