galaxy_info:
  role_name: build_directories
  author: Calvin Remsburg
  description: builds directories to host the configuration files throughout the build
  company: Juniper Networks

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  galaxy_tags:
    - juniper
    - network
    - files
    - configuration

dependencies: []
